#EJERCICIO 2
#Alejandro Nava Castillo
import math as m
import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,4*m.pi)
s=np.cos(2*x)+(np.sin(3*x))
v=-2*np.sin(2*x)+3*np.cos(3*x)
plt.plot(x,s,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(x,v,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica A")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
x=np.linspace(0,2)
s=x*(m.e**(3*x))
g=(m.e**m.e*x)*(1-3*x)
plt.plot(x,s,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(x,g,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica B")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
t=np.linspace(0,4*m.pi)
f=(np.sin(3*t))*np.cos(2*t)
g=(1/2)*(np.cos(t))+(5/2)*(np.cos(5*t))
plt.plot(t,f,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(t,g,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica C")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
t=np.linspace(0,2*m.pi)
u=1+2*np.sin(t)*np.cos(t)
i=(1+2*np.sin(t))*np.sin(t)
plt.plot(t,u,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(t,i,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica D")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
