#EJERCICIO 3
#Alejandro Nava Castillo
import math as m
import matplotlib.pyplot as plt
import numpy as np
t=np.linspace(0,2*m.pi)
x=((np.cos(t))**3)
y=((np.sin(t))**3)
plt.plot(t,x,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(t,y,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica A")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
t=np.linspace(-2*m.pi,2*m.pi)
x=t+2*np.sin(2*t)
y=t+2*np.cos(5*t)
plt.plot(t,x,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(t,y,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica B")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
t=np.linspace(0,2*m.pi)
x=np.sin(3*t)
y=np.sin(4*t)
plt.plot(t,x,linewidth=3,color='r',label='Linea Sen-Cos')
plt.plot(t,y,linewidth=3,color='g',label='Linea 2Sen-2Cos')
plt.legend('Grafico Comparativo')
plt.title("Grafica C")
plt.xlabel('Tiempo')
plt.ylabel('Aburrimiento')
plt.grid(True)
plt.show()
